@startuml corporate_app
!include ../domain/recruiting_context.pu

package application {
    ' 企業向けアプリケーション
    namespace CorporateApp {
        class JobUsecase {
            + JobDto findBy(jobId)
            + List<JobDto> findBy(jobSearchForm)
            + JobDto create(jobForm)
            + JobDto update(jobForm)
        }

        class ResumeUsecase {
            + Resume findBy(candidateId)
            + List<Resume> findBy(resumeSearchForm)
        }

        JobUsecase ..> RecruitingContext.JobRepository
        ResumeUsecase ..> RecruitingContext.ResumeRepository
    }
}

CorporateApp ...> RecruitingContext

@enduml