@startuml sample
!include core_context.pu

namespace JobHuntContext {
    class Resume <<AggregateRoot>> {
    }

    class ResumeRepository <<Repository>> {
    }

    class Job <<AggregateRoot>> {
        title
    }

    class JobRepository <<Repository>> {
    }

    class Candidate <<AggregateRoot>> {
        name
    }
    
    class CandidateRepository <<Repository>> {
    }

    class CandidateRegistrationService {
        + CandidateId register(username, password)
    }

    class JobApplication <<AggregateRoot>> {
        jobId
        resumeId
        candidateId
    }

    class JobApplicationEvent <<ValueObject>> {
        applicationId
        eventType
        timestamp 
    }

    class JobApplyService <<DomainService>> {
        + JobApplication apply(resumeId, jobId)
    }

    Candidate *- CoreContext.CandidateId
    CandidateRegistrationService ..> CandidateRepository

    Resume *-- CoreContext.ResumeId
    Resume *-- CoreContext.CandidateId
    ResumeRepository ..> Resume

    JobApplication *-- CoreContext.JobApplicationId
    JobApplication *- CoreContext.ResumeId
    JobApplication *- CoreContext.JobId

    Job *-- CoreContext.JobId
    JobRepository ..> Job

    JobApplyService ..> JobApplication :creates
    JobApplication ..> JobApplicationEvent :publish
}

@enduml