@startuml sample
!include core_context.pu

namespace JobHuntContext {
    class Resume <<AggregateRoot>> {
    }

    class ResumeRepository <<Repository>> {
    }

    class ResumeEvent <<DomainEvent>> {
        resumeId
        timestamp
    }

    class Job <<AggregateRoot>> {
        title
    }

    class JobApplicationSpec <<Specification>> {
        + boolean isSatisfiedBy(resume)
    }

    class JobRepository <<Repository>> {
    }

    class Candidate <<AggregateRoot>> {
        name
    }
    
    class CandidateRepository <<Repository>> {
    }

    class CandidateRegistrationService {
        + CandidateId register(username, password)
    }

    Candidate *- CoreContext.CandidateId
    CandidateRegistrationService ..> CandidateRepository

    Resume *-- CoreContext.ResumeId
    Resume *-- CoreContext.CandidateId
    ResumeRepository ..> Resume

    Resume ..> ResumeEvent :publishes
    ResumeEvent <|-- ResumeCreated
    ResumeEvent <|-- ResumeUpdated
    ResumeEvent <|-- ResumeDeleted

    Job *-- CoreContext.JobId
    Job *-- JobApplicationSpec
    JobRepository ..> Job
    Job ..> RecruitingContext.JobEvent :subscribes

    JobApplyService ..> CoreContext.JobApplicationRepository
    JobApplyService ..> JobApplicationSpec :uses
}

@enduml