@startuml sample
!include core_context.pu

namespace RecruitingContext {

    class Resume <<AggregateRoot>> {
    }

    class Job <<AggregateRoot>> {
    }

    class JobRepository <<Repository>> {
    }

    class JobEvent <<DomainEvent>> {
    }

    class RecruiterId <<ValueObject>> {
    }

    class Recruiter <<AggregateRoot>> {
        recruiterId
        corporateId
    }

    class CorporateId <<ValueObject>> {
    }

    class Corporate <<AggregateRoot>> {
        corporateId
    }

    Resume *-- CoreContext.ResumeId
    Resume *..> JobHuntContext.ResumeEvent :subscribes

    Job *-- CoreContext.JobId
    Job *-- CorporateId
    Job *-- RecruiterId
    JobRepository ..> Job

    Job ..> JobEvent :publishes
    JobEvent <|-- JobCreated
    JobEvent <|-- JobPublished
    JobEvent <|-- JobUnpublished
    JobEvent <|-- JobDeleted

    Corporate *-- CorporateId

    Recruiter *-- RecruiterId
    Recruiter *- CorporateId

}

@enduml
